services:
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_password
      - MINIO_DEFAULT_BUCKETS=boot
    command: server --address "0.0.0.0:9000" --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "alias", "set", "local", "http://localhost:9000", "your_username", "your_password" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data
    networks:
      - default
      - npm_network

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123pass
      MYSQL_DATABASE: bootdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 123pass
    volumes:
      - ./data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3883:3333"
    depends_on:
      - database
      - minio
    networks:
      - default
      - npm_network
    environment:
      - NODE_ENV=production
      - MINIO_PUBLIC_URL=https://boot-s3.solveweb.com.br

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_SERVER_URL: https://boot-back.solveweb.com.br
    ports:
      - "8883:80"
    depends_on:
      - server
    networks:
      - default
      - npm_network
    environment:
      - NODE_ENV=production

networks:
  npm_network:
    external: true
    name: solveweb-site_web

volumes:
  minio_data:
